CREATE OR REPLACE TRIGGER DELETE_HOTEL
BEFORE DELETE ON HOTEL
FOR EACH ROW
BEGIN
  INSERT INTO LOG_DELETE(DELETE_VALUES, TYPE, INSERT_AT)VALUES(''||
  :old.ID||','||
  :old.NOMBRE||','||
  :old.TELEFONO||','||:old.ADMINISTRADOR||','||
  :old.CAPACIDAD||','||
  :old.DIRECCION||','||
  :old.CORREO_ELECTRONICO||','||
  :old.PAGINA_WEB||','||
  :old.CREATED_AT||','||
  :old.UPDATED_AT, 'Hotel', SYSDATE);
END;
