CREATE OR REPLACE TRIGGER DELETE_EMRPRESA
BEFORE DELETE ON EMPRESA_TRANSPORTES
FOR EACH ROW
BEGIN
  INSERT INTO LOG_DELETE(DELETE_VALUES, TYPE, INSERT_AT)VALUES(''||
  :old.ID||','||
  :old.NOMBRE||','||
  :old.TELEFONO||','||
  :old.DIRECCION||','||
  :old.CREATED_AT||','||
  :old.UPDATED_AT, 'Empresa de Tansportes', SYSDATE);
END;
