CREATE OR REPLACE TRIGGER DELETE_CONDUCTOR
BEFORE DELETE ON CONDUCTOR
FOR EACH ROW
BEGIN
  INSERT INTO LOG_DELETE(DELETE_VALUES, TYPE, INSERT_AT)VALUES(''||
  :old.ID||','||
  :old.CEDULA||','||
  :old.NOMBRES||','||
  :old.TELEFONO||','||
  :old.FECHA_NACIMIENTO||','||
  :old.DIRECCION||','||
  :old.CORREO_ELECTRONICO||','||
  :old.PERFIL_ACADEMICO||','||
  :old.CREATED_AT||','||
  :old.UPDATED_AT, 'Conductor', SYSDATE);
END;
